### ISSUE TITLE
How do i select a target Wifi?

### ISSUE THREAD

**Issue by SwenSwenTheGreat** [TechnicalUserX/batch_wifi_brute_forcer#1]
I don't seem to be able to find where to put the target Wifi

**Comment by ExtremePro11299** [comment]
Type in "scan". It will show you the list of networks you can choose from. Type the number of the network in and you have it selected.

**Comment by CrookedAlt** [comment]
it shows me ' ( was not expected at this time '

**Comment by TechnicalUserX** [comment]
Hello, the new version of the program should fix many problems. I suggest you to take a look at it. Thank you.

**Comment by ExtremePro11299** [comment]
Also this is fixed, close issue plz
