### ISSUE TITLE
Hey! I was wondering if it was ok to use this in my project, giving the credit ofc

### ISSUE THREAD

**Issue by CrookedAlt** [TechnicalUserX/batch_wifi_brute_forcer#10]
https://github.com/CrookedAlt/ExtraCommands
https://github.com/CrookedAlt/ExtraCommands/tree/master/batch_wifi_brute_forcer-main

**Comment by TechnicalUserX** [comment]
Hello there, it is OK as this project contains the MIT license. :) As long as you leave my name on it at some part of the code, it is good for me. Thanks by the way.

**Comment by TechnicalUserX** [comment]
By the way, I fixed so many bugs and removed some unnecessary parts from the brute forcer project, so this new version should be better now. I will enhance the "Batch MAC Spoofer" some day too.
