### ISSUE TITLE
saves the wordlist path as result for password found

### ISSUE THREAD

**Issue by rohrbaugh26** [TechnicalUserX/batch_wifi_brute_forcer#16]
as title says, code runs fine until i go to retrieve the password.  it saves the file path for the wordlist in the results folder as the found "password"

**Comment by ExtremePro11299** [comment]
There is no results folder. Did you mean the result file?

**Comment by rohrbaugh26** [comment]
yes your correct, sorry for delayed response

**Comment by ExtremePro11299** [comment]
What is your operating system?

**Comment by rohrbaugh26** [comment]
windows 11

**Comment by ExtremePro11299** [comment]
Ok, any more details about how to reproduce this?

**Comment by rohrbaugh26** [comment]
I actually just fixed it!  The default wordlist didnt contain any text other than "not defined" and it was what was causing the issues.  Now that I created a new word list and replaced the default its working properly.  I have tested it on 3 different networks now with the correct password inside the new word list, and each time was successful.  Thank you!!

**Comment by rohrbaugh26** [comment]
![Screenshot 2024-05-19 133417](https://github.com/TechnicalUserX/batch_wifi_brute_forcer/assets/121594978/56c03a87-fac1-457b-bdc6-7d6dd2bb3b7a)


This is how it was saving prior to fixing the wordlist folder issue.

**Comment by ExtremePro11299** [comment]
Do you mean wordlist.txt by default wordlist?

**Comment by ExtremePro11299** [comment]
Also, the DefaultWordlist.txt file is not meant to be used as a wordlist

**Comment by ExtremePro11299** [comment]
it is just a setting to set a path in there so that you dont have to specify a wordlist every time you open the program.

**Comment by ExtremePro11299** [comment]
Read the default wordlist section of my README.

**Comment by rohrbaugh26** [comment]
I see that now, I misread it when going through the first time.  Yes wordlist.txt is what im referring to

**Comment by ExtremePro11299** [comment]
wordlist.txt is functional wordlist, while DefaultWordlist.txt contains not_defined. Do you know what DefautWordlist.txt is for now?

**Comment by rohrbaugh26** [comment]
Yes appreciate your help!

**Comment by ExtremePro11299** [comment]
Ok, close issue
