### ISSUE TITLE
When running as administrator, the path is not right

### ISSUE THREAD

**Issue by ExtremePro11299** [TechnicalUserX/batch_wifi_brute_forcer#4]
# MAC spoofing not working

I have screwed up the MAC spoofing by checking if the BF_Files folder exists, because it checks if it exists before it checks the permissions. I might fix this and send a pull request.

**Comment by TechnicalUserX** [comment]
New version should fix this bug.

**Comment by ExtremePro11299** [comment]
There is no mac spoofing, so this is *technicallyXed*.
